apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jenkins-web
  namespace: jenkins
spec:
  rules:
  - host: jenkins.rancher.<dominio>
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 9090